export default Object.freeze({
  Home: "Home",
  GiftCard: "GiftCard",
  HelpCenter: "HelpCenter",
  Questions: "Questions",
  QuestionsAdd: "QuestionsAdd",
  HotelList: "HotelList",
  HotelDetails: "HotelDetails",
  CarRentals: "CarRentals",
  TravelOffers: "TravelOffers",
  CarSearch: "CarSearch",
  CarSearchResults: "CarSearchResults",
  SelectedCar: "SelectedCar",
  YourContributions: "YourContributions",
  AppFeedback: "AppFeedback",
  FilterCars: "FilterCars",
  PaymentGateway: "PaymentGateway",
  CarCustomerDetails: "CarCustomerDetails",
  CarBookingFinished: "CarBookingFinished",
  TravelCommunity: "TravelCommunity",
  GiveTips: "GiveTips",
  GiveQuestions: "GiveQuestions",
  DiscoverTravel: "DiscoverTravel",
  MyTravel: "MyTravel",
  Communities: "Communities",
  MyCommunities: "MyCommunities",

  // Nisuga
  SignInSignUpHome: "SignInSignUpHome",
  SignIn: "SignIn",
  SignUp: "SignUp",
  ListYourProperty: "ListYourProperty",
  Notifications:"Notifications"
});
