export default Object.freeze({
  Home: "Home",
  GiftCard: "GiftCard",
  HelpCenter: "HelpCenter",
  HotelList: "HotelList",
  HotelDetails: "HotelDetails",
  CarRentals: "CarRentals",
  TravelOffers: "TravelOffers",
  CarSearch: "CarSearch",
  CarSearchResults: "CarSearchResults",
  SelectedCar: "SelectedCar",
  YourContributions: "YourContributions",
  AppFeedback: "AppFeedback",
  FilterCars: "FilterCars",
  PaymentGateway: "PaymentGateway",
  CarCustomerDetails: "CarCustomerDetails",
  CarBookingFinished: "CarBookingFinished",
});
